services:
  backend-user:
    build: ./backend-user
    ports:
      - "5000:5000"
    volumes:
      - ./backend-user:/app
      - /app/node_modules
    networks:
      - app-net
  
  backend-task:
    build: ./backend-task
    ports:
      - "5001:5001"
    volumes:
      - ./backend-task:/app
      - /app/node_modules
    networks:
      - app-net

  bff:
    build: ./bff
    container_name: bff
    ports:
      - "3000:3000"
    depends_on:
      - backend-user
    volumes:
      - ./bff:/app
      - /app/node_modules
    networks:
      - app-net
    environment:
      - GRPC_BACKEND_URL=backend-user:5000

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:3000"
    depends_on:
      - bff
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-net

networks:
  app-net:
